import type { Metadata } from 'next'
import { Session } from 'next-auth'

import Navbar from '@/app/components/Navbar';
import serverSession from '@/app/lib/session';
import AuthContext from '@/app/context/AuthContext';
import '@/app/globals.css';
import { StrictMode } from 'react';

export const metadata: Metadata = {
  title: 'Bede',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await serverSession();

  return (
    <html lang="en">
      <StrictMode>
        <body suppressHydrationWarning={true}>
          <AuthContext session={session as Session}>
            <main className="flex min-h-screen flex-col items-center">
              <Navbar session={session as Session} />
              {children}
            </main>
          </AuthContext>
        </body>
      </StrictMode>
    </html>
  )
}
