import { headers } from 'next/headers'
import type { Metadata } from 'next'
import { Session } from 'next-auth'

import Navbar from './components/Navbar';
import AuthContext from './AuthContext';
import './globals.css';

export async function getServerSession(): Promise<Session> {
  const response = await fetch(`http://localhost:3000/api/auth/session`, {
    headers: {
      cookie: headers().get('cookie') ?? '',
    },
  });

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}

export const metadata: Metadata = {
  title: 'Bede',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <AuthContext session={session}>
        <main className="flex min-h-screen flex-col items-center">
          <Navbar session={session} />
          {children}
        </main>
        </AuthContext>
      </body>
    </html>
  )
}
